Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/**/*'
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 30

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: '#consistent-string-literals'
  Enabled: false
Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: false
Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'
