language: ruby
rvm: 2.4

os: linux
addons:
  firefox: '56.0'
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

env: RAILS_ENV=test
script:
  - bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
